---
version: '3.1'

services:

  site:
    build: .
    command: bundle exec rake servequick
    volumes:
      - '${PWD}/src:/usr/local/site/src:ro'
      - '${PWD}/build/config:/usr/local/site/build/config:ro'
      - '${PWD}/Gemfile:/usr/local/site/Gemfile:ro'
      - '${PWD}/Rakefile:/usr/local/site/Rakefile:ro'
    ports:
      - '4000:4000'
    

