title: The Functional Style
author:
- Richard Wild
subtitle: Functional programming explained for the pragmatic programmer.
abstract: Functional programming explained for the pragmatic programmer.
keywords: 
- Functional programming
- Craftsmanship
- Pragmatic
subject: Software Development 
description: Functional programming explained for the pragmatic programmer..
category: Software Development