title: Test
author:
- Christopher Eyre
- Sam Davies
subtitle: A guide to modern software development
abstract: A personal set of practices for software development
keywords: 
- Agile
- Lean
- Craftsmanship
- Pragmatic
subject: Software Development 
description: A personal set of practices for software development.
category: Software Development